import { Category, LiveStream, VodStream, SeriesItem, SeriesDetail, SubscriptionPlan } from '../types/iptv';

export const DEMO_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan_30d',
    name: 'รายเดือน 30 วัน (1 เดือน)',
    nameEn: '30 Days Pass',
    price: 129,
    period: '30 วัน',
    icon: '📱',
    devices: 'รับชมได้ 1 เครื่อง',
    subRate: 'เฉลี่ยตกวันละ ~4.3 บาทเท่านั้น',
    buttonText: 'สมัครแพ็กเกจ 30 วัน',
    features: [
      'ดูได้ 1 อุปกรณ์พร้อมกัน',
      'รองรับ TV / มือถือ / คอมพิวเตอร์',
      'ช่องฟรีทีวี & กีฬา Monomax',
      'สตรีมมิ่งความเร็วสูง ภาพคมชัด Full HD',
    ],
  },
  {
    id: 'plan_90d',
    name: '90 วัน (3 เดือน)',
    nameEn: '90 Days Pass',
    price: 250,
    period: '90 วัน',
    icon: '🖥️',
    devices: 'รับชมได้ 1 เครื่อง',
    subRate: 'เฉลี่ยเพียงเดือนละ ~83 บาท!',
    popular: true,
    tag: 'ประหยัดคุ้มค่า',
    buttonText: 'สมัครแพ็กเกจ 90 วัน',
    features: [
      'ดูได้ 1 อุปกรณ์พร้อมกัน',
      'ประหยัดกว่ารายเดือนปกติ',
      'สัญญาณสตรีมมิ่งความเร็วสูง',
      'ช่องสด กีฬา หนัง ซีรีส์ครบวงจร',
    ],
  },
  {
    id: 'plan_180d',
    name: '180 วัน (6 เดือน)',
    nameEn: '180 Days Pass',
    price: 399,
    period: '180 วัน',
    icon: '📺',
    devices: 'รับชมได้ 1 เครื่อง',
    subRate: 'เฉลี่ยเพียงเดือนละ ~66 บาท',
    buttonText: 'สมัครแพ็กเกจ 180 วัน',
    features: [
      'ดูยาวนานครึ่งปี ไม่ต้องต่ออายุบ่อย',
      'ครบทุกหมวด กีฬา หนัง การ์ตูน สารคดี',
      'ดูได้ 1 อุปกรณ์พร้อมกัน',
      'เซิร์ฟเวอร์เสถียร ไม่สะดุดตลอด 24 ชม.',
    ],
  },
  {
    id: 'plan_1y',
    name: '1 ปี (12 เดือน)',
    nameEn: '1 Year (12 Months)',
    price: 699,
    period: '1 ปี (365 วัน)',
    icon: '👑',
    devices: 'รับชมได้ 1 เครื่อง',
    subRate: 'ตกเพียงเดือนละ ~58 บาทเท่านั้น!',
    tag: 'สุดคุ้มรายปี',
    buttonText: 'สมัครแพ็กเกจ 1 ปี (699.-)',
    features: [
      'ดูยาวๆ 365 วัน สบายใจตลอดปี',
      'เฉลี่ยถูกที่สุดสำหรับ 1 อุปกรณ์',
      'ดูได้ 1 เครื่องพร้อมกัน',
      'ช่องกีฬาพรีเมียม หนังชนโรง ซีรีส์ 4K',
    ],
  },
  {
    id: 'plan_1y_vip',
    name: '1 ปี (12 เดือน) VIP',
    nameEn: '1 Year VIP Dual Screen',
    price: 799,
    period: '1 ปี (365 วัน)',
    icon: '🔥',
    devices: 'รับชมพร้อมกันได้ 2 เครื่อง VIP',
    subRate: 'เฉลี่ยเพียงเครื่องละ ~33 บ./เดือน!',
    popular: true,
    tag: 'VIP 2 จอ 🔥',
    buttonText: 'สมัครแพ็กเกจ 1 ปี VIP (799.-)',
    features: [
      'ดูได้ 2 เครื่องพร้อมกัน (TV + มือถือ)',
      'สิทธิ์ความเร็วเซิร์ฟเวอร์ VIP',
      'เหมาะสำหรับหารกัน 2 คน',
      'รองรับ TiviMate / IPTV Smarters / Web',
    ],
  },
  {
    id: 'plan_lifetime',
    name: 'ไอดี VIP พิเศษ ตลอดชีพ VIP',
    nameEn: 'Lifetime VIP Unlimited',
    price: 1200,
    period: 'จ่ายครั้งเดียวจบตลอดชีพ',
    icon: '🏆',
    devices: 'รับชมพร้อมกันได้ 2 จอ แบบไร้ขีดจำกัด',
    subRate: 'ไม่ต้องจ่ายรายเดือนตลอดชีวิต!',
    bestValue: true,
    tag: '🌟 คุ้มค่าที่สุดตลอดกาล',
    buttonText: '💬 สมัครแพ็กเกจตลอดชีพ 1200.- คลิก',
    features: [
      'ดูได้ 2 จอพร้อมกัน VIP ไม่หลุด',
      'จ่ายครั้งเดียวดูยาวตลอดชีพ',
      'พรีเมียม สิทธิ์เซิร์ฟเวอร์สูงสุด',
      'ซัพพอร์ตพิเศษแลกเปลี่ยนเคส 24 ชม.',
    ],
  },
];

export const DEMO_LIVE_CATEGORIES: Category[] = [
  { category_id: 'live_th_all', category_name: '🇹🇭 ทีวีไทยดิจิทัล (Digital TV)', count: 12 },
  { category_id: 'live_sports', category_name: '⚽ กีฬา & ฟุตบอลสด (Sports HD/4K)', count: 10 },
  { category_id: 'live_movies', category_name: '🎬 ภาพยนตร์ & ซีรีส์สด (Movie Channels)', count: 8 },
  { category_id: 'live_docu', category_name: '🦁 สารคดี & การเรียนรู้ (Discovery/NatGeo)', count: 6 },
  { category_id: 'live_news', category_name: '🌍 ข่าวสารรอบโลก (News & Finance)', count: 6 },
  { category_id: 'live_4k', category_name: '✨ ช่องรายการพิเศษ 4K UHD', count: 5 },
  { category_id: 'live_adult', category_name: '🔞 18+ Adult Channels (ติดรหัส PIN)', count: 4 },
];

export const DEMO_VOD_CATEGORIES: Category[] = [
  { category_id: 'vod_recent', category_name: '🌟 หนังเข้าใหม่ล่าสุด 2026-2025', count: 10 },
  { category_id: 'vod_thai', category_name: '🇹🇭 ภาพยนตร์ไทยยอดนิยม', count: 8 },
  { category_id: 'vod_action', category_name: '💥 แอ็กชัน & ผจญภัย (Action/Adventure)', count: 8 },
  { category_id: 'vod_scifi', category_name: '🚀 ไซไฟ & แฟนตาซี (Sci-Fi & Fantasy)', count: 6 },
  { category_id: 'vod_horror', category_name: '👻 ระทึกขวัญ & สยองขวัญ (Horror)', count: 6 },
  { category_id: 'vod_4k', category_name: '💎 หนัง 4K HDR Atmos Master', count: 5 },
];

export const DEMO_SERIES_CATEGORIES: Category[] = [
  { category_id: 'series_trending', category_name: '🔥 ซีรีส์ยอดฮิตติดเทรนด์ 2026', count: 6 },
  { category_id: 'series_korea', category_name: '🇰🇷 ซีรีส์เกาหลี (K-Drama พากย์ไทย/ซับไทย)', count: 8 },
  { category_id: 'series_thai', category_name: '🇹🇭 ซีรีส์ไทย & ละครดัง', count: 6 },
  { category_id: 'series_china', category_name: '🇨🇳 ซีรีส์จีนย้อนยุค & โมเดิร์น', count: 6 },
  { category_id: 'series_west', category_name: '🇺🇸 ซีรีส์ฝรั่ง (HBO/Netflix/Disney)', count: 6 },
];

export const TEST_HLS_URLS = [
  'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
  'https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
];

export const DEMO_LIVE_STREAMS: LiveStream[] = [
  {
    stream_id: 'demo_live_3hd',
    name: 'ช่อง 3 HD (Ch3 Thailand 33) 1080p',
    stream_icon: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_th_all',
    epg_channel_id: 'th_ch3',
  },
  {
    stream_id: 'demo_live_7hd',
    name: 'ช่อง 7 HD (Ch7 Thailand 35) 1080p',
    stream_icon: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_th_all',
    epg_channel_id: 'th_ch7',
  },
  {
    stream_id: 'demo_live_one31',
    name: 'ช่อง ONE 31 HD (ละคร/ซิทคอม/ข่าว) 1080p',
    stream_icon: 'https://images.unsplash.com/photo-1578022761797-b8636ac1773c?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_th_all',
    epg_channel_id: 'th_one31',
  },
  {
    stream_id: 'demo_live_thairath',
    name: 'ไทยรัฐทีวี 32 HD (Thairath TV) 1080p',
    stream_icon: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_th_all',
    epg_channel_id: 'th_thairath',
  },
  {
    stream_id: 'demo_live_amarin',
    name: 'อมรินทร์ทีวี 34 HD (Amarin TV) 1080p',
    stream_icon: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_th_all',
    epg_channel_id: 'th_amarin',
  },
  {
    stream_id: 'demo_live_workpoint',
    name: 'Workpoint TV 23 HD (วาไรตี้เกมโชว์)',
    stream_icon: 'https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_th_all',
    epg_channel_id: 'th_workpoint',
  },
  {
    stream_id: 'demo_live_true4u',
    name: 'True4U 24 HD (ถ่ายทอดสดกีฬา/มวยไทย)',
    stream_icon: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_th_all',
    epg_channel_id: 'th_true4u',
  },
  {
    stream_id: 'demo_live_mono29',
    name: 'Mono 29 HD (ฟรีทีวีหนังดี ซีรีส์ดัง)',
    stream_icon: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_th_all',
    epg_channel_id: 'th_mono29',
  },
  {
    stream_id: 'demo_live_tpf1',
    name: '⚽ True Premier Football HD 1 [พรีเมียร์ลีก]',
    stream_icon: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_sports',
    epg_channel_id: 'sp_tpf1',
  },
  {
    stream_id: 'demo_live_tpf2',
    name: '⚽ True Premier Football HD 2 [พรีเมียร์ลีก]',
    stream_icon: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_sports',
    epg_channel_id: 'sp_tpf2',
  },
  {
    stream_id: 'demo_live_bein1',
    name: '⚽ beIN SPORTS 1 HD [ยูฟ่าแชมเปียนส์ลีก/ลาลิกา]',
    stream_icon: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_sports',
    epg_channel_id: 'sp_bein1',
  },
  {
    stream_id: 'demo_live_bein3',
    name: '🏎️ beIN SPORTS 3 HD [F1 รถสูตรหนึ่ง & เทนนิส]',
    stream_icon: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_sports',
    epg_channel_id: 'sp_bein3',
  },
  {
    stream_id: 'demo_live_spotv',
    name: '🏸 SPOTV HD [แบดมินตัน BWF / โมโตจีพี]',
    stream_icon: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_sports',
    epg_channel_id: 'sp_spotv',
  },
  {
    stream_id: 'demo_live_hbo',
    name: '🎬 HBO HD Asia [หนังใหม่ตลอด 24 ชม.]',
    stream_icon: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_movies',
    epg_channel_id: 'mv_hbo',
  },
  {
    stream_id: 'demo_live_cinemax',
    name: '🎬 Cinemax HD [แอ็คชั่น ระทึกขวัญ]',
    stream_icon: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_movies',
    epg_channel_id: 'mv_cinemax',
  },
  {
    stream_id: 'demo_live_natgeo',
    name: '🦁 National Geographic Wild HD [สารคดีสัตว์โลก]',
    stream_icon: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_docu',
    epg_channel_id: 'dc_natgeo',
  },
  {
    stream_id: 'demo_live_discovery',
    name: '🔬 Discovery Channel Asia HD [วิทยาศาสตร์และโลก]',
    stream_icon: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_docu',
    epg_channel_id: 'dc_discovery',
  },
  {
    stream_id: 'demo_live_4k_test',
    name: '✨ ULTRA HD 4K SPORTS & MOVIES [4K 60FPS]',
    stream_icon: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_4k',
    epg_channel_id: 'uhd_sports',
  },
  {
    stream_id: 'demo_live_adult_1',
    name: '🔞 Playboy TV HD (ผู้ใหญ่)',
    stream_icon: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_adult',
    is_adult: true,
  },
  {
    stream_id: 'demo_live_adult_2',
    name: '🔞 Midnight Blue 4K (ผู้ใหญ่)',
    stream_icon: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=500&auto=format&fit=crop&q=60',
    category_id: 'live_adult',
    is_adult: true,
  },
];

export const DEMO_VOD_STREAMS: VodStream[] = [
  {
    stream_id: 'vod_1',
    name: 'สัปเหร่อ (The Undertaker) [พากย์ไทย] 1080p',
    stream_icon: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=60',
    rating: 8.8,
    year: '2023',
    category_id: 'vod_thai',
    container_extension: 'mp4',
  },
  {
    stream_id: 'vod_2',
    name: 'ธี่หยด 2 (Tee Yod 2) [Full HD Master พากย์ไทย]',
    stream_icon: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=500&auto=format&fit=crop&q=60',
    rating: 8.6,
    year: '2024',
    category_id: 'vod_horror',
    container_extension: 'mp4',
  },
  {
    stream_id: 'vod_3',
    name: 'Dune: Part Two (ดูน ภาค 2) [4K UHD ซับไทย/พากย์ไทย]',
    stream_icon: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=60',
    rating: 8.9,
    year: '2024',
    category_id: 'vod_4k',
    container_extension: 'mp4',
  },
  {
    stream_id: 'vod_4',
    name: 'John Wick: Chapter 4 (จอห์น วิค 4) [4K Atmos]',
    stream_icon: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&auto=format&fit=crop&q=60',
    rating: 8.7,
    year: '2023',
    category_id: 'vod_action',
    container_extension: 'mp4',
  },
  {
    stream_id: 'vod_5',
    name: 'หลานม่า (LAHN MAH / How to Make Millions Before Grandma Dies)',
    stream_icon: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=500&auto=format&fit=crop&q=60',
    rating: 9.1,
    year: '2024',
    category_id: 'vod_thai',
    container_extension: 'mp4',
  },
  {
    stream_id: 'vod_6',
    name: 'Avatar: The Way of Water (อวตาร: วิถีแห่งสายน้ำ) [4K]',
    stream_icon: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=60',
    rating: 8.5,
    year: '2023',
    category_id: 'vod_scifi',
    container_extension: 'mp4',
  },
  {
    stream_id: 'vod_7',
    name: 'Deadpool & Wolverine (เดดพูล & วูล์ฟเวอรีน) [Master 4K]',
    stream_icon: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=60',
    rating: 8.4,
    year: '2024',
    category_id: 'vod_recent',
    container_extension: 'mp4',
  },
  {
    stream_id: 'vod_8',
    name: 'Oppenheimer (ออปเพนไฮเมอร์) [IMAX Enhanced 4K]',
    stream_icon: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500&auto=format&fit=crop&q=60',
    rating: 9.0,
    year: '2023',
    category_id: 'vod_recent',
    container_extension: 'mp4',
  },
];

export const DEMO_SERIES_ITEMS: SeriesItem[] = [
  {
    series_id: 'ser_1',
    name: 'Moving (ยอดมนุษย์พลังพิเศษ) [พากย์ไทย/ซับไทย ครบทุกตอน]',
    cover: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=500&auto=format&fit=crop&q=60',
    rating: 8.9,
    releaseDate: '2023',
    category_id: 'series_korea',
    genre: 'Action, Sci-Fi, Drama',
    plot: 'เรื่องราวของกลุ่มวัยรุ่นที่มีพลังพิเศษซ่อนอยู่ และพ่อแม่ที่มีอดีตอันเจ็บปวด ต้องร่วมมือกันปกป้องครอบครัวจากศัตรูร้าย',
  },
  {
    series_id: 'ser_2',
    name: 'Marry My Husband (สามีคนนี้แจกฟรีให้เธอ) [ครบจบ]',
    cover: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=500&auto=format&fit=crop&q=60',
    rating: 8.6,
    releaseDate: '2024',
    category_id: 'series_korea',
    genre: 'Drama, Romance, Fantasy',
    plot: 'เมื่อหญิงสาวถูกสามีและเพื่อนสนิทหักหลังจนเสียชีวิต เธอได้ย้อนเวลากลับไปเมื่อ 10 ปีก่อนเพื่อชำระแค้นและเปลี่ยนชะตาชีวิต',
  },
  {
    series_id: 'ser_3',
    name: 'House of the Dragon Season 2 (ตระกูลมังกร ซีซั่น 2)',
    cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=60',
    rating: 8.8,
    releaseDate: '2024',
    category_id: 'series_west',
    genre: 'Action, Fantasy, Drama',
    plot: 'สงครามแย่งชิงบัลลังก์เหล็กแห่งตระกูลทาร์แกเรียนที่ปะทุขึ้นด้วยไฟมังกรและเลือดเนื้อ',
  },
  {
    series_id: 'ser_4',
    name: 'มาตาลดา (To the Moon and Back) [พากย์ไทย]',
    cover: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&auto=format&fit=crop&q=60',
    rating: 9.0,
    releaseDate: '2023',
    category_id: 'series_thai',
    genre: 'Feel Good, Comedy, Romance',
    plot: 'เรื่องราวอบอุ่นหัวใจของหญิงสาวมองโลกในแง่บวก ที่นำพาความสุขและความรักมาสู่คุณหมอหัวใจที่เย็นชา',
  },
  {
    series_id: 'ser_5',
    name: 'Shogun (โชกุน 2024) [4K UHD Master]',
    cover: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?w=500&auto=format&fit=crop&q=60',
    rating: 9.1,
    releaseDate: '2024',
    category_id: 'series_trending',
    genre: 'History, War, Drama',
    plot: 'การแย่งชิงอำนาจยุคศักดินาในญี่ปุ่นโบราณ กัปตันเรือชาวอังกฤษต้องเข้ามาพัวพันกับแผนการชิงตำแหน่งโชกุน',
  },
];

export const DEMO_SERIES_DETAILS: Record<string, SeriesDetail> = {
  ser_1: {
    seasons: { '1': {} },
    info: {
      name: 'Moving (ยอดมนุษย์พลังพิเศษ)',
      plot: 'เรื่องราวของกลุ่มวัยรุ่นที่มีพลังพิเศษซ่อนอยู่ และพ่อแม่ที่มีอดีตอันเจ็บปวด',
      rating: '8.9',
      genre: 'Action, Sci-Fi',
      releaseDate: '2023',
    },
    episodes: {
      '1': [
        { id: 'm_ep1', episode_num: 1, title: 'ตอนที่ 1: การค้นพบพลังที่ซ่อนเร้น', container_extension: 'mp4' },
        { id: 'm_ep2', episode_num: 2, title: 'ตอนที่ 2: ความลับของครอบครัว', container_extension: 'mp4' },
        { id: 'm_ep3', episode_num: 3, title: 'ตอนที่ 3: เงามืดที่คืบคลาน', container_extension: 'mp4' },
        { id: 'm_ep4', episode_num: 4, title: 'ตอนที่ 4: การต่อสู้ครั้งแรก', container_extension: 'mp4' },
        { id: 'm_ep5', episode_num: 5, title: 'ตอนที่ 5: พลังที่ไม่อาจซ่อน', container_extension: 'mp4' },
        { id: 'm_ep6', episode_num: 6, title: 'ตอนที่ 6: การไล่ล่าข้ามคืน', container_extension: 'mp4' },
      ],
    },
  },
  ser_2: {
    seasons: { '1': {} },
    info: {
      name: 'Marry My Husband (สามีคนนี้แจกฟรีให้เธอ)',
      plot: 'เมื่อหญิงสาวถูกหักหลังและได้รับโอกาสกลับมาเปลี่ยนชะตากรรม',
      rating: '8.6',
      genre: 'Drama, Romance',
      releaseDate: '2024',
    },
    episodes: {
      '1': [
        { id: 'mmh_ep1', episode_num: 1, title: 'ตอนที่ 1: โชคชะตาที่ย้อนกลับ', container_extension: 'mp4' },
        { id: 'mmh_ep2', episode_num: 2, title: 'ตอนที่ 2: แผนการแก้เผ็ดเพื่อนสนิท', container_extension: 'mp4' },
        { id: 'mmh_ep3', episode_num: 3, title: 'ตอนที่ 3: ผู้ช่วยคนใหม่ที่คาดไม่ถึง', container_extension: 'mp4' },
        { id: 'mmh_ep4', episode_num: 4, title: 'ตอนที่ 4: งานเลี้ยงเปิดโปงความจริง', container_extension: 'mp4' },
      ],
    },
  },
  ser_3: {
    seasons: { '1': {}, '2': {} },
    info: {
      name: 'House of the Dragon',
      plot: 'สงครามบัลลังก์มังกรแห่งตระกูลทาร์แกเรียน',
      rating: '8.8',
      genre: 'Fantasy, Drama',
    },
    episodes: {
      '1': [
        { id: 'hotd_s1_ep1', episode_num: 1, title: 'S1 Ep 1: The Heirs of the Dragon', container_extension: 'mp4' },
        { id: 'hotd_s1_ep2', episode_num: 2, title: 'S1 Ep 2: The Rogue Prince', container_extension: 'mp4' },
      ],
      '2': [
        { id: 'hotd_s2_ep1', episode_num: 1, title: 'S2 Ep 1: A Son for a Son', container_extension: 'mp4' },
        { id: 'hotd_s2_ep2', episode_num: 2, title: 'S2 Ep 2: Rhaenyra the Cruel', container_extension: 'mp4' },
        { id: 'hotd_s2_ep3', episode_num: 3, title: 'S2 Ep 3: The Burning Mill', container_extension: 'mp4' },
        { id: 'hotd_s2_ep4', episode_num: 4, title: 'S2 Ep 4: The Red Dragon and the Gold', container_extension: 'mp4' },
      ],
    },
  },
};
